language: ruby
dist: trusty
rvm:
- 2.4.2
before_script:
- bundle exec rake db:create --all
- psql -c "CREATE USER carlos;" -U postgres
- bundle exec rake db:migrate
script:
- bundle exec rake ci:tests
services:
- postgresql
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: MBhJkA6ZgKX5+1Q40gLfNMK+A4rCGhDZf3Sl+xTcMIf2uZ3mxqlDj8OLdnd9otY5GWHlfRGemCy2/EOI6Nsc9PM85DA2xUKZ3i3kiX2HMun9IV2tuJ4WH6jvHTl0ie7MCFgV+OP06nhAIjxydv4yZZgkj2Wu2cPvD8Fe3ZRvHKX984QZSPm7TQG9C0zeIARtsq/53UPCgO0TmwmCdSpM4wMAjiXTwb/GCyvcSdiAmVmJ8oV2YvaXnVPb1nFejexEsC7KOfjyuNdsRKl9dS6tfpT97v1Nm+1sVJy81aRTpyYwXX3OGmx2GpeZMSQyFlBTGmb4kTBV1mvnGS86/GPLsQBwWMLTXwKyi98Cqs2+z+2RCr6OY2eTBTt/u+NC3iw8fZl7YTztU+dlm7CwHG0/ZWCJPrQZbt6KJO311NBZElOoRzzWuOs7fPRmdLBTvX8HwVcyXDeo/3tKuj3jB2X1h2B5nL7XrDFumYrVc4oKxMET9FNNgScb/NvlbiS1bZ5rFcVPdToTW/OuN/mbOPGQ3/kQyuqA/8MI4MRtN0TMDnONfIqp3aI2VScD0xZ+ye5YQ1Y5YY37I49kvqTB4sPswUGSvEKjTFax+mWox6FPfb8ddsUFaQc377i2X2CSg9YJlnv/Dk3eAggjmbXM9X1tiyi72yeYLmX8m8KqDFa+nSw=
  app:
    develop: biblioteca-popular-develop
    master: biblioteca-popular-master
  on:
    repo: tip-grupo-2/tip_grupo_2
  run:
  - rails db:migrate
